import { Sparkles, CheckCircle2, RefreshCw } from 'lucide-react'
import type { InterviewPrepProps, BriefingStatus, InterviewType } from '../types'
import { BriefingStatusBanner } from './BriefingStatusBanner'
import { MatchHeader } from './MatchHeader'
import { StrengthsList } from './StrengthsList'
import { GapsPanel } from './GapsPanel'
import { QuestionsList } from './QuestionsList'

export function InterviewPrep({
  candidate,
  jobRequisition,
  briefing,
  strengths,
  gaps,
  riskAreas,
  interviewQuestions,
  onCopyQuestion,
  onCopyBriefing,
  onRegenerateBriefing,
  onMarkReviewed,
}: InterviewPrepProps) {
  const isPending = briefing.status === 'pending'
  const isOutdated = briefing.status === 'outdated'

  const interviewTypePill: Record<InterviewType, { label: string; className: string }> = {
    hr_screening: {
      label: 'HR Screening Briefing',
      className:
        'bg-indigo-50 text-indigo-700 border-indigo-200 dark:bg-indigo-950/40 dark:text-indigo-300 dark:border-indigo-800/50',
    },
    technical: {
      label: 'Technical Interview Briefing',
      className:
        'bg-blue-50 text-blue-700 border-blue-200 dark:bg-blue-950/40 dark:text-blue-300 dark:border-blue-800/50',
    },
  }

  const pill = interviewTypePill[briefing.interviewType]

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-6 sm:py-8">
        {/* Interview type pill */}
        {pill && (
          <div className="mb-3">
            <span
              className={`inline-flex items-center px-2.5 py-1 text-xs font-medium rounded-full border ${pill.className}`}
            >
              {pill.label}
            </span>
          </div>
        )}

        {/* Status banner */}
        <BriefingStatusBanner
          status={briefing.status as BriefingStatus}
          generatedAt={briefing.generatedAt}
          interviewType={briefing.interviewType}
          onRegenerate={onRegenerateBriefing}
          onCopyBriefing={onCopyBriefing}
        />

        {isPending ? (
          /* Pending empty state */
          <div className="mt-12 flex flex-col items-center text-center px-4">
            <div className="w-14 h-14 rounded-2xl bg-amber-50 dark:bg-amber-900/20 flex items-center justify-center mb-4">
              <Sparkles
                className="w-7 h-7 text-amber-500 dark:text-amber-400"
                strokeWidth={1.5}
              />
            </div>
            <h3 className="text-base font-semibold text-slate-900 dark:text-slate-50 tracking-tight">
              Waiting for candidate profile
            </h3>
            <p className="mt-2 text-sm text-slate-500 dark:text-slate-400 max-w-sm leading-relaxed">
              The interview briefing will be generated once the candidate's resume and LinkedIn profile have been ingested. Go to the Profile tab to upload missing data.
            </p>
          </div>
        ) : (
          /* Ready / Outdated content */
          <div className={isOutdated ? 'opacity-60' : undefined}>
            {/* Match header */}
            <div className="mt-5">
              <MatchHeader
                candidate={candidate}
                jobRequisition={jobRequisition}
                matchQuality={briefing.matchQuality}
                matchSummary={briefing.matchSummary}
              />
            </div>

            {/* Strengths and Gaps side-by-side on larger screens */}
            <div className="mt-5 grid grid-cols-1 lg:grid-cols-2 gap-4">
              <StrengthsList strengths={strengths} />
              <GapsPanel gaps={gaps} riskAreas={riskAreas} />
            </div>

            {/* Interview questions — the hero section */}
            <div className="mt-8">
              <QuestionsList
                questions={interviewQuestions}
                onCopyQuestion={onCopyQuestion}
                onCopyBriefing={onCopyBriefing}
              />
            </div>

            {/* AI attribution */}
            <div className="mt-6 flex items-center justify-center gap-1.5 text-[10px] text-slate-400 dark:text-slate-500 tracking-wide uppercase">
              <Sparkles className="w-3 h-3" strokeWidth={1.5} />
              Generated by Vor AI ·{' '}
              {new Date(briefing.generatedAt).toLocaleDateString('en-US', {
                month: 'short',
                day: 'numeric',
                year: 'numeric',
                hour: 'numeric',
                minute: '2-digit',
              })}
            </div>

            {/* Footer actions */}
            <div className="mt-6 pb-4 flex flex-col sm:flex-row items-stretch sm:items-center justify-center gap-2">
              <button
                onClick={() => onMarkReviewed?.()}
                className="inline-flex items-center justify-center gap-2 px-5 py-2.5 text-sm font-medium rounded-lg bg-blue-600 text-white hover:bg-blue-700 dark:bg-blue-500 dark:hover:bg-blue-600 transition-colors"
              >
                <CheckCircle2 className="w-4 h-4" strokeWidth={1.5} />
                Mark as Reviewed
              </button>
              <button
                onClick={() => onRegenerateBriefing?.()}
                className="inline-flex items-center justify-center gap-2 px-5 py-2.5 text-sm font-medium rounded-lg border border-slate-200 dark:border-slate-600 text-slate-600 dark:text-slate-300 bg-white dark:bg-slate-800 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors"
              >
                <RefreshCw className="w-4 h-4" strokeWidth={1.5} />
                Regenerate Briefing
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
